# Generated by Django 5.2.2 on 2025-08-14 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slayground_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('event_type', models.CharField(choices=[('PRIVATE', 'SLAYvents (Private)'), ('PUBLIC', 'SLAYbrations (Public)')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_published', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='slayground_app.location')),
            ],
            options={
                'ordering': ['-start_datetime', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EventInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('category', models.CharField(choices=[('BACHELORETTE', 'Bachelorette'), ('BIRTHDAY', 'Birthday'), ('CORPORATE', 'Corporate'), ('SCHOOL', 'School/Team'), ('CUSTOM', 'Custom')], max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('attendees_count', models.PositiveIntegerField(default=10)),
                ('city_or_studio', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('BOOKED', 'Booked'), ('CLOSED', 'Closed')], default='NEW', max_length=10)),
                ('template_event', models.ForeignKey(blank=True, limit_choices_to={'event_type': 'PRIVATE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='slayground_app.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10)),
                ('paid_cents', models.PositiveIntegerField(default=0)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=120)),
                ('stripe_receipt_url', models.URLField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='slayground_app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'is_published'], name='slayground__event_t_82b697_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime'], name='slayground__start_d_8fca02_idx'),
        ),
        migrations.AddIndex(
            model_name='eventinquiry',
            index=models.Index(fields=['status', 'category'], name='slayground__status_545e83_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['status'], name='slayground__status_829b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event', 'status'], name='slayground__event_i_a2e17b_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='event_reg_quantity_gte_1'),
        ),
    ]
