# Generated by Django 5.2.2 on 2025-08-14 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slayground_app', '0002_event_eventinquiry_eventregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Admin label, e.g. 'Beginner Heels Tue/Thu 6:30pm'", max_length=120)),
                ('start_date', models.DateField(help_text='First week to consider')),
                ('end_date', models.DateField(blank=True, help_text='Last date to consider (optional)', null=True)),
                ('byweekday', models.JSONField(default=list, help_text='List of integers 0=Mon..6=Sun')),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('interval_weeks', models.PositiveIntegerField(default=1, help_text='1 = every week, 2 = every other week, etc.')),
                ('capacity', models.PositiveIntegerField(default=20)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(fields=('class_type', 'start_datetime'), name='unique_classsession_type_start'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrence_rules', to='slayground_app.classtype'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_rules', to='slayground_app.instructor'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_rules', to='slayground_app.location'),
        ),
        migrations.AddField(
            model_name='excludeddate',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_dates', to='slayground_app.recurrencerule'),
        ),
        migrations.AlterUniqueTogether(
            name='excludeddate',
            unique_together={('rule', 'date')},
        ),
    ]
