# Generated by Django 5.2.2 on 2025-08-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slayground_app', '0003_excludeddate_recurrencerule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurrencerule',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='recurrencerule',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='recurrencerule',
            name='location',
        ),
        migrations.AddField(
            model_name='classsession',
            name='recurrence_enabled',
            field=models.BooleanField(default=False, help_text='If on, this session is a seed for repeats.'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='recurrence_every_n_weeks',
            field=models.PositiveIntegerField(default=1, help_text='1 = weekly, 2 = every other week, etc.'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='recurrence_skips',
            field=models.JSONField(blank=True, default=list, help_text='List of dates (YYYY-MM-DD) to skip'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='recurrence_until',
            field=models.DateField(blank=True, help_text='Last date to generate (inclusive).', null=True),
        ),
        migrations.DeleteModel(
            name='ExcludedDate',
        ),
        migrations.DeleteModel(
            name='RecurrenceRule',
        ),
    ]
