# Generated by Django 5.2.2 on 2025-08-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slayground_app', '0004_remove_recurrencerule_class_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='external_url',
            field=models.URLField(blank=True, help_text='Optional generic link (blog, drive, etc.)'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/images/'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='content/attachments/'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='content/audio/'),
        ),
    ]
